### ISSUE TITLE
Some minor update on TSConfig

### ISSUE THREAD

**Issue by motss** [toajs/quic#7]
- To use `--esModuleInterop` plus `--allowSyntheticDefaultImport`. See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html
- To use `"moduleResolution": "node"`

**Comment by zensh** [comment]
Thank you

**Comment by zensh** [comment]
I just turn off `esModuleInterop` because of https://travis-ci.org/toajs/quic/jobs/366706904

**Comment by motss** [comment]
@zensh Don't think you should. `--esModuleInterop` is to tackle libraries who does not have `default` import. Depends on which one you're using in `ilog` as I can see `.mjs` and `.js` version, you can use `import ilog from 'ilog'` instead of `import * as ilog from 'ilog'`.

The safest way is to `import { ilog } from 'ilog';` if this is possible.
